### PR TITLE
update darkroomjs and demo

### PR DESCRIPTION
**Pull request by xiaody**
It seems that the demo doesn't work well with the lastest version of darkroomjs, so I just modify the demo  to fit it.

### CODE REVIEW

**Comment by natecox** [comment]
Trying out the demo of this on a clean install I'm having issues with uploading images in succession. Uploading a new image should clear the current image and replace it, whereas in this version uploading a new image is adding a new darkroom instance below the existing one.
screen shot 2015-09-08 at 8 52 01 am

**Comment by natecox** [comment]
Also, the cropping utility is no longer opening by default as in the current demo.

**Comment by natecox** [comment]
One more: confirming a crop with the green checkmark doesn't place the cropped image below the upload buttons as intended.

**Comment by natecox** [comment]
If I were to hazard a guess, I'd say that the event signals aren't being picked up properly.

If you can get it working I'd be happy to merge.

**Comment by xiaody** [comment]
Yes, you are right.

I have pushed one more commit to address the issues you mentioned, but due to some changes in darkroom v2.0.x it's still not 100% equal to the old demo.

We need to contribute some code to darkroom if we want to make our demo perfect.
Or stick to darkroomjs#e0b057ac8e0b79f07e0b3b7b5978eb80f41b6e41 (a 1.x version) in bower.json :(

**Comment by natecox** [comment]
Seems like it's working pretty well now, I appreciate the effort to get it working for me.

What are the issues that you've faced with the new Darkroom specifically?

**Comment by xiaody** [comment]
I'm not very familiar with darkroom yet, so my following sentences can be inaccurate:

The biggest trouble is that there is no convenient way to replace the image on the fly. We have to destroy the old instance and create a new one to achieve that. Making it worse, some darkroom async methods (including #destroy) lack flow control like callback/event/promise, so we have to use polling;

There are some other some issues like the navigation events have been removed (by mistake, I guess?) in v2.0. Another example is what I do in https://github.com/natecox/angular-darkroomjs/pull/3/files#diff-b9da8711597c9398b134d96e62f53b39R52 for https://github.com/MattKetmo/darkroomjs/blob/v2.0.1/lib/js/core/darkroom.js#L97

**Comment by natecox** [comment]
Not having an event for destroy kind of sucks, but it's not a deal killer for me to just crush the instance and recreate when they select a new image. I count that as a destructive action anyways.

It looks like you can use `selectZone` in place of `requireFocus`, although the only way I could find that was by navigating the source code. If the crop plugin doesn't have focus it will call `requireFocus` internally. See: https://github.com/MattKetmo/darkroomjs/blob/10f743a96d1c5c9ec22d0e4e6cd5b2619077c4be/lib/js/plugins/darkroom.crop.js#L426

**Comment by natecox** [comment]
Looks like this is good to go.

**Comment by natecox** [comment]
This is now up on bower as version 0.0.7

**Pull request merged**
